@startuml

| cmd/index |

start

: Read configuration file ;

repeat

  if (local page) then
    : Start local express server & host directory resources;
    : Map page path to localhost ;
  endif
  | RecorderHandler |
  : Stream screen screenshots from PhantomJS to FFMPEG ;
  | OverlayHandler |
  : Map Videos to screen-records based on color/chromakeys ;
  | MergeHandler |
  : Merge videos into single output video ;
  | AMergeHandler |
  : Crop & AMerge audio streams into the output video ;

  | cmd/index |
  : Stop Express server (if exists) ;

repeat while ( more entries?)

@enduml
